spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: assma.idbensalah2000@gmail.com
    password: ppke nuwc yltn etay
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  kafka:
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.odc.notificationserver.dto.ReservationConfirmedEvent

app:
  mail:
    from: assma.idbensalah2000@gmail.com