server:
  port: 8086

stripe:
  api:
    key: sk_test_xxxxxxxxxxxxxxxxx

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/football-realme
