services:
  # =====================
  # DATABASES
  # =====================
  postgresql-match:
    image: postgres
    container_name: ms_pg_sql_match
    environment:
      POSTGRES_DB: matchdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres-match:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  postgresql-reservation:
    image: postgres
    container_name: ms_pg_sql_reservation
    environment:
      POSTGRES_DB: reservationdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres-reservation:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

  # =====================
  # KAFKA
  # =====================
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - microservices-net
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=1

  # =====================
  # CONFIG SERVER
  # =====================
  config-server:
    container_name: config-server
    build: server/Services/config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-net

  # =====================
  # EUREKA SERVER
  # =====================
  discovery:
    container_name: discovery
    build: server/Services/discovery
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  # =====================
  # AUTH
  # =====================
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    ports:
      - "8085:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - microservices-net

  # =====================
  # GATEWAY
  # =====================
  gateway-service:
    container_name: api_gateway
    build: server/Services/gateway-server
    ports:
      - "8084:8084"
    depends_on:
      - match-service
      - reservation-service
      - payment-service
      - notification-service
      - keycloak
    networks:
      - microservices-net

  # =====================
  # MICROSERVICES
  # =====================
  match-service:
    container_name: match-server
    build: server/Services/match-server
    ports:
      - "8082:8080"
    depends_on:
      - postgresql-match
      - config-server
      - discovery
    networks:
      - microservices-net

  reservation-service:
    container_name: reservation-server
    build: server/Services/reservation-server
    ports:
      - "8083:8080"
    depends_on:
      - postgresql-reservation
      - config-server
      - discovery
      - kafka
    networks:
      - microservices-net

  payment-service:
    container_name: payment-server
    build: server/Services/payment-server
    ports:
      - "8086:8080"
    depends_on:
      - kafka
      - config-server
    networks:
      - microservices-net

  notification-service:
    container_name: notification-server
    build: server/Services/notification-server
    ports:
      - "8087:8080"
    depends_on:
      - kafka
      - config-server
    networks:
      - microservices-net

# =====================
# NETWORKS & VOLUMES
# =====================
networks:
  microservices-net:
    driver: bridge

volumes:
  postgres-match:
  postgres-reservation:
  pgadmin: