spring.application.name=match-server
spring.main.allow-bean-definition-overriding=true
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/matchdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ========== OAUTH2 CLIENT (pour appeler Config Server / Eureka) ==========
#spring.security.oauth2.client.registration.keycloak.client-id=match-service
#spring.security.oauth2.client.registration.keycloak.client-secret=5MoSC6Scp1qLJycwfWXyK5c2Av9yfWpU
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.keycloak.scope=openid
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8085/realms/football-realme

# ========== RESOURCE SERVER (pour verifier les JWT entrants) ==========
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8085/realms/football-realme

spring.config.import=configserver:http://localhost:8888

# =====================
# Eureka Client Config
# =====================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


logging.level.org.springframework.security=DEBUG