spring:
  application:
    name: match-server
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://ms_pg_sql_match:5432/matchdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/football-realme

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE